# Generated by Django 4.1.1 on 2022-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
